### ISSUE TITLE
 if rst_data['flood'] == 1:       KeyError: 'flood' 

### ISSUE THREAD

**Issue by jibanli** [istarli/mobile_vlan#2]
mobile_vlan.py 

in _packet_in_handler
    if rst_data['flood'] == 1:
KeyError: 'flood'

**Comment by jibanli** [comment]
Could you tell me how to solve the problem?

**Comment by istarli** [comment]
You can look at the functoin "isLogined" further to find out when the key "flood" will be set.
Actually this project is currently not maintained.
